name: Build and Deploy
on: [push]

jobs:
  build-model:
    name: Build and upload model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<20"
        ## python -m pip install -r requirements.txt
        ## pip install rasa
        pip install rasa-x --extra-index-url https://pypi.rasa.com/simple
        pip install pytablewriter==0.46.1
    - name: Cross-validate NLU model
      run: |
        rasa test nlu -f 5 --cross-validation
        python format_results.py
    - name: post cross-val results to PR
      uses: amn41/comment-on-pr@comment-file-contents
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: results.md